import { SRTO_DataTypes } from "./srto-dataTypes"

export const SRTO_Signals: SRTO_DataTypes.SIGNALS = {
    "srto_screen1": {
        // "ABS_KTC_BRY": [],
        // "1614_KO_KATOWICE": [],
        //
        // "1655_KZ_KATOWICEZAWODZIE": [],
        // "ABS_KATOWICEZAWODZIE_SOSNOWIECGLOWNY": [],
        // "3993_SG_SOSNOWIECGLOWNY": [],
        // "4010_Spl1_SOSNOWIECPOLUDNIOWY": [],
        // "ABS_SOSNOWIECGLOWNY_BEDZIN": [],
        // "124_B_BEDZIN": [],
        // "ABS_BEDZIN_DABROWAGORNICZA": [],
        // "719_DG_DABROWAGORNICZA": [],
        // "ABS_DABROWAGORNICZA_DABROWAGORNICZAZABKOWICE": [],
        // "721_DGHK_DABROWAGORNICZAHUTAKATOWICE": [],
        // "734_DZ_DABROWAGORNICZAZABKOWICE": [],
        // "ABS_DABROWAGORNICZAZABKOWICE_LAZYLC": [],
        // "3398_Pmi_PRZEMIARKI": [],
        // "2375_LC_LAZYLC": [],
        // "2371_LB_LAZY": [],
        // "ABS_LAZYLB_LAZYLA": [],
        // "2374_LA_LAZYLA": [],
        // "5262_Zw_ZAWIERCIE": [],
        // "ABS_ZAWIERCIE_MYSZKOW": [],
        // "ABS_ZAWIERCIE_GORAWLODOWSKA": [],
        // "1193_GW_GORAWLODOWSKA": [],
        // "ABS_GORAWLODOWSKA_PSARY": [],
        // "3436_Ps_PSARY": [],
        // "ABS_PSARY_STARZYNY": [],
        // "STARZYNY_SPROWA__KOZLOW_ENTRY": [],
        // "ABS_PSARY_KNAPOWKA": [],
        // "1772_Kn_KNAPOWKA": [],
        // "ABS_KNAPOWKA_CZARNCA": [],
        // "ABS_Zes_WP": [],
        // "ABS_Kn_WP": [],
        // "WLOSZCZOWA_POLNOC": [],
        // "ABS_WP_Ol": [],
        // "OLSZAMOWICE": [],
        // "ABS_Ol_Op_Pl": [],
        // "OPOCZNO_POLUDNIE": [],
        // "ABS_Op_Id": [],
        // "IDZIKOWICE": [],
        // "ABS_Id_Rd": [],
        // "ABS_Id_St": [],
        // "STRZALKI": [],
        // "ABS_St_Sz_BR": [],
        // "SZELIGI": [],
        // "ABS_Sz_Mr": [],
        // "ABS_Sz_Kr": [],
        // "KORYTOW": [],
        // "ABS_Kr_Zy_Gr": [],
        // "GRODZISK_MAZOWIECKI": [],
        // "ABS_Gr_Pr": [],
        // "PRUSZKOW": [],
        // "ABS_Pr_Jz_Wl": [],
        // "WARSZAWA_WLOCHY": [],
        // "ABS_Wl_WZD": [],
        // "WARSZAWA_ZACHODNIA": []
    },
    "srto_screen2": {
        // "3792_Se_SEDZICE": [],
        // "3827_Si_SIERADZ": [],
        // "2582_Me_APO_MEKA": [],
        // "5291_ZW_ZDUNSKAWOLA": [],
        // "5292_ZWK_ZDUNSKAWOLAKARSZNICE--779_Di_DIONIZOW": [],
        // "919_Ga_GAJEWNIKI": [],
        // "292_Bo_APO_BORSZEWICE": [],
        // "2360_La_LASK": [],
        // "802_Db_APO_KOLUMNA_DOBRON": [],
        // "3093_Pa_PABIANICE": [],
        // "2330_Lb_LODZLUBLINEK": [],
        // "3577_Rt_RETKINIA": [],
        // "2432_LK_LODZKALISKA": [],
        // "2463_LZ_LODZZABIENIEC": [],
        // "5311_Zg_ZGIERZ": [],
        // "5317_ZP_ZGIERZ_POLNOC__1057_Gl_GLINNIK": [],
        // "ABS_LODZKALISKA_LODZCHOJNY": [],
        // "2426_LCH_LODZCHOJNY": [],
        // "2427_LD_LODZDABROWA": [],
        // "2457_LW_LODZWIDZEW": [],
        // "2437_LM_LODZMARYSIN": [],
        // "ABS_LODZWIDZEW_LODZANDRZEJOW_GALKOWEG": [],
        // "924_G_GALKOWEG": [],
        // "ABS_GALKOWEG_KOLUSZKI": [],
        // "2439_LO_LODZOLECHOW": [],
        // "3617_Ro_ROZPRZA": [],
        // "ABS_ROZPRZA_PIOTRKOWTRYBUNALSKI": [],
        // "3223_PT_PIOTRKOWTRYBUNALSKI": [],
        // "ABS_PIOTRKOWTRYBUNALSKI_BABY": [],
        // "60_Ba_BABY": [],
        // "ABS_BABY_ROKICINY": [],
        // "3594_Ro_ROKICINY": [],
        // "ABS_ROKICINY_KOLUSZKI": [],
        // "1803_KO_KOLUSZKI": [],
        // "ABS_KOLUSZKI_ROGOW": [],
        // "3590_Rg_ROGOW": [],
        // "ABS_ROGOW_PLYCWIA": [],
        // "3251_Pl_PLYCWIA": [],
        // "ABS_PLYCWIA_SKIERNIEWICE": [],
        // "3877_Sk_SKIERNIERWICE": [],
    },
    "srto_screen3": {},
    "srto_screen4": {}
}