import { SRTO_DataTypes } from "./srto-dataTypes"

const phFontSize = 12

export const SRTO_Nodes: SRTO_DataTypes.NODES = {
    "srto_screen1": {
        // "ADDITIONAL_NODES": [],
        // "KTC_BRY": [],
        // "KATOWICE": [],
        // "KO_KZ": [],
        // "KATOWICE_ZAWODZIE": [],
        // "KZ_SG": [],
        // "SOSNOWIEC_GLOWNY": [],
        // "SOSNOWIEC_POLUDNIOWY": [],
        // "SG_B": [],
        // "BEDZIN": [],
        // "B_DG": [],
        // "DABROWA_GORNICZA": [],
        // "DG_DZ": [],
        // "DABROWA_GORNICZA_HUTA_KATOWICE": [],
        // "DABROWA_GORNICZA_ZABKOWICE": [],
        // "DZ_LC": [],
        // "LAZY_LC": [],
        // "LC_LB": [],
        // "LAZY_LB": [],
        // "LB_LA": [],
        // "LAZY_LA": [],
        // "LA_Zw": [],
        // "ZAWIERCIE": [],
        // "Zw_My": [],
        // "Zw_GW": [],
        // "GORA_WLODOWSKA": [],
        // "GW_Ps": [],
        // "PSARY": [],
        // "STARZYNY_SPROWA__KOZLOW_ENTRY": [],
        // "STARZYNY_SPROWA": [],
        // "Ps_Kn": [],
        // "KNAPOWKA": [],
        // "Kn_Cz": [],
        // "Kn_WP": [],
        // "Zes_WP": [],
        // "WLOSZCZOWA_POLNOC": [],
        // "WP_Ol": [],
        // "OLSZAMOWICE": [],
        // "Ol_OP": [],
        // "OPOCZNO_POLUDNIE": [],
        // "OP_Id": [],
        // "IDZIKOWICE": [],
        // "Id_Rd": [],
        // "Id_St": [],
        // "STRZALKI": [],
        // "St_Se": [],
        // "SZELIGI": [],
        // "Se_Mr_Kr": [],
        // "KORYTOW": [],
        // "Kr_Gr": [],
        // "GRODZISK_MAZOWIECKI": [],
        // "Gr_Pr": [],
        // "PRUSZKOW": [],
        // "Pr_Jz_Wl": [],
        // "WARSZAWA_WLOCHY": [],
        // "Wl_WZD": []
    },
    "srto_screen2": {
        // "ADDITIONAL_MARKER": [],
        // "SEDZICE": [],
        // "SEDZICE_SIERADZ": [],
        // "SIERADZ": [],
        // "SIERADZ_ZDUNSKAWOLA": [],
        // "ZDUNSKA_WOLA": [],
        // "ZDUNSKAWOLA_GAJEWNIKI__ZWK_Dionizów": [],
        // "GAJEWNIKI": [],
        // "GAJEWNIKI_LASK": [],
        // "LASK": [],
        // "LASK_PABIANICE": [],
        // "PABIANICE": [],
        // "PABIANICE_LODZLUBLINEK": [],
        // "LODZ_LUBLINEK": [],
        // "LODZLUBLINEK_RETKINIA": [],
        // "RETKINIA": [],
        // "RETKINIA_LODZKALISKA": [],
        // "LODZ_KALISKA": [],
        // "LODZ_ZABIENIEC": [],
        // "LODZZABIENIEC_ZGIERZ": [],
        // "LODZWIDZEW_LODZMARYSIN_ZGIERZ": [],
        // "ZGIERZ": [],
        // "ZGIERZ_POLNOC__GLINNIK": [],
        // "LODZKALISKA_LODZCHOJNY": [],
        // "LODZ_CHOJNY": [],
        // "LODZCHOJNY_LODZWIDZEW": [],
        // "LODZ_WIDZEW": [],
        // "LODZWIDZEW_LODZANDRZEJOW_GALKOWEG": [],
        // "GALKOWEG": [],
        // "GALKOWEG_KOLUSZKI": [],
        // "LODZ_OLECHOW": [],
        // "ROZPRZA": [],
        // "ROZPRZA_PIOTRKOW_TRYBUNALSKI": [],
        // "PIOTRKOW_TRYBUNALSKI": [],
        // "PIOTROKOWTRYBUNALKSI_BABY": [],
        // "BABY": [],
        // "BABY_ROKICINY": [],
        // "ROKICINY": [],
        // "ROKICINY_KOLUSZKI": [],
        // "1803_KOLUSZKI": [],
        // "KOLUSZKI_ROGOW": [],
        // "ROGOW": [],
        // "ROGOW_PLYCWIA": [],
        // "PLYCWIA": [],
        // "PLYCWIA_SKIERNIEWICE": [],
        // "3877_Sk_SKIERNIEWICE": [],
        "__TEMPLATE__": [],
    },
    "srto_screen3": {
        "ADDITIONAL_MARKERS": [
            {
                nodeID: 'txt-WIP_S2',
                nodeType: 'simpleText',
                nodePos: { x: 1280, y: 300 },
                text: '--- THIS SCREEN IS NOT YET AVAILABLE ---',
                textSize: 40
            },
            {
                nodeID: 'txt-WIP_S2',
                nodeType: 'simpleText',
                nodePos: { x: 1280, y: 350 },
                text: 'Expect this screen to be accessible on update v0.5.0-alpha',
                textSize: 30
            },
        ]
    },
    "srto_screen4": {
        "ADDITIONAL_MARKERS": [
            {
                nodeID: 'txt-WIP_S2',
                nodeType: 'simpleText',
                nodePos: { x: 1280, y: 300 },
                text: '--- THIS SCREEN IS NOT YET AVAILABLE ---',
                textSize: 40
            },
            {
                nodeID: 'txt-WIP_S2',
                nodeType: 'simpleText',
                nodePos: { x: 1280, y: 350 },
                text: 'Expect this screen to be accessible on update v0.6.0-alpha',
                textSize: 30
            },
        ]
    }
}