import { SRTO_DataTypes } from "./srto-dataTypes";
const npt_color = 'rgb(70, 70, 70)'

export const SRTO_Tracks: SRTO_DataTypes.TRACKS = {
    "srto_screen1": {
        "TRACK_SPLITTER": [
            {
                trackID: 'TRACK_SPLITTER_LINE',
                /*
                Splitter Myszkow / GoraWlodowska
                */
                trackSVG: `
                M1750,770 1990,770 1990,710 2100,710`,
                trackColor: 'rgb(255, 210, 62)'
            }
        ],
        //"TRACKS_KTC_BRY_KATOWICE": [],
        //"KATOWICE": [],
        //"TRACKS_KATOWICE_KATOWICEZAWODZIE": [],
        //"KATOWICE_ZAWODZIE": [],
        //"TRACKS_KATOWICEZAWODZIE_SOSNOWIECGLOWNY": [],
        //"SOSNOWIEC_GLOWNY_SOSNOWIEC_POLUDNIOWY": [],
        // "TRACKS_SOSNOWIECGLOWNY_BEDZIN": [],
        // "BEDZIN": [],
        // "BEDZIN_DABROWAGORNICZA": [],
        //"DABROWA_GORNICZA": [],
        //"DABROWAGORNICZA_DABROWAGORNICZAZABKOWICE": [],
        //"DABROWA_GORNICZA_ZABKOWICE": [],
        //"TRACKS_DABROWAGORNICZAZABKOWICE_LAZYLC": [],
        // "DABROWAGORNICZATOWAROWA_PRZEMIARKI": [],
        // "LAZY_LC": [],
        // "TRACKS_LAZYLC_LAZYLB": [],
        // "LAZY_LB": [],
        // "TRACKS_LAZYLB_LAZYLA": [],
        // "LAZY_LA": [],
        // "TRACKS_LAZYLA_ZAWIERCIE": [],
        // "ZAWIERCIE": [],
        // "TRACKS_ZAWIERCIE_MYSZKOW_GORAWLODOWSKA": [],
        // "GORA_WLODOWSKA": [],
        // "TRACKS_GORAWLODOWSKA_PSARY": [],
        // "KOZLOW_PSARY": [],
        // "PSARY": [],
        // "TRACKS_PSARY_KNAPOWKA": [],
        // "KNAPOWKA": [],
        // "TRACKS_KNAPOWKA_WLOSZCZOWAPOLNOC": [],
        // "WLOSZCZOWA_POLNOC": [],
        // "TRACKS_WLOSZCZOWAPOLNOC_OLSZAMOWICE": [],
        // "OLSZAMOWICE": [],
        // "TRACKS_OLSZAMOWICE_OPOCZNOPOLUDNIE": [],
        // "OPOCZNO_POLUDNIE": [],
        // "TRACKS_OPOCZNOPOLUDNIE_IDZIKOWICE": [],
        // "IDZIKOWICE": [],
        // "TRACKS_IDZIKOWICE_RADZICE_STRZALKI": [],
        // "STRZALKI": [],
        // "TRACKS_STRZALKI_SZELIGI": [],
        // "SZELIGI": [],
        // "TRACKS_SZELIGI_MARKOW_KORYTOW": [],
        // "KORYTOW": [],
        // "TRACKS_KORYTOW_GRODZISK_MAZOWIECKI": [],
        // "GRODZISK_MAZOWIECKI": [],
        // "TRACKS_GRODZISKMAZOWIECKI_PRUSZKOW": [],
        // "PRUSZKOW": [],
        // "TRACKS_PRUSZKOW_WARSZAWAWLOCHY": [],
        // "JOZEFIONW": [],
        // "WARSZAWA_WLOCHY": [],
        // "TRACKS_WARSZWLOCHY_WARSZZACHODNIA": [],
        // "WARSZAWA_ZACHODNIA": []
    },
    "srto_screen2": {
        // "SEDZICE": [],
        // "TRACKS_SEDZICE_SIERADZ": [],
        // "SIERADZ": [],
        // "TRACKS_SIERADZ_ZDUNSKAWOLA": [],
        // "ZDUNSKA_WOLA": [],
        // "TRACKS_ZDUNSKAWOLA_GAJEWNIKI": [],
        // "GAJEWNIKI": [],
        // "TRACKS_GAJEWNIKI_LASK": [],
        // "LASK": [],
        // "TRACKS_LASK_PABIANICE": [],
        // "PABIANICE": [],
        // "TRACKS_PABIANICE_LODZLUBLINEK": [],
        // "LODZ_LUBLINEK": [],
        // "TRACKS_LODZLUBLINEK_RETKINIA": [],
        // "RETKINIA": [],
        // "TRACKS_RETKINIA_LODZKALISKA": [],
        // "LODZ_KALISKA": [],
        // "TRACKS_LODZKALISKA_LODZZABIENIEC": [],
        // "LODZ_ZABIENIEC": [],
        // "TRACKS_LODZZABIENIEC_ZGIERZ": [],
        // "LODZWIDZEW_LODZMARYSIN_ZGIERZ": [],
        // "ZGIERZ": [],
        // "TRACKS_ZGIERZ_ZgPolnoc_Glinnik": [],
        // "ZGIERZ_POLNOC__GLINNIK": [],
        // "TRACKS_LODZKALISKA_LODZCHOJNY": [],
        // "LODZ_CHOJNY": [],
        // "TRACKS_LODZCHOJNY_LODZWIDZEW__FABRYCZNA": [],
        // "LODZ_WIDZEW": [],
        // "LODZCHOJNY_LODZWIDZEW_>_LODZOLECHOW": [],
        // "LODZ_OLECHOW": [],
        // "TRACKS_LODZWIDZEW_LODZOLECHOW__GALKOWEK": [],
        // "924_GALKOWEG": [],
        // "GALKOWEK_ZAKOWICEPOLUDNIOWE_>_KOLUSZKI_1": [],
        // "3617_ROZPRZA": [],
        // "TRACKS_ROZPRZA_PIOTRKOWTRYBUNALSKI": [],
        // "3223_PIOTRKOW_TRYBUNLASKI": [],
        // "TRACKS_PIOTRKOWTRYBUNALSKI_BABY": [],
        // "60_BABY": [],
        // "TRACKS_BABY_ROCKICINY": [],
        // "3594_ROKICINY": [],
        // "TRACKS_TOWARDS_KOLUSZKI": [],
        // "1803_KOLUSZKI": [],
        // "TRACKS_KOLUSZKI_ROGOW": [],
        // "3590_ROGOW": [],
        // "TRACKS_ROGOW_PLYCWIA": [],
        // "3251_PLYCWIA": [],
        // "TRACKS_PLYCWIA_SKIERNIEWICE": [],
        // "3877_Sk_SKIERNIERWICE": []
    },
    "srto_screen3": {},
    "srto_screen4": {}
}